import QtQuick
import "."

// Density 3: the one sentence a chart is making, under it. Generated by `core/narrate.py`, never
// written in the view, and never more than twelve words -- that limit is enforced in Python, so a
// long thought becomes a fact in a reading panel rather than a paragraph here.
Txt {
    color: Theme.ink
    font.pixelSize: Theme.fBody
    font.weight: Font.Medium
    wrapMode: Text.WordWrap
    elide: Text.ElideNone
    lineHeight: 1.35
    visible: text !== ""
}
